CREATE USER adminruta WITH PASSWORD 'ruta2024*';
CREATE DATABASE db_ruta WITH ENCODING='UTF8' LC_COLLATE='es_CO.UTF-8' LC_CTYPE='es_CO.UTF-8' TEMPLATE=template0;
GRANT ALL PRIVILEGES ON DATABASE db_ruta TO adminruta;